Portal/BlueCardPortal/Controllers/ApplicationController.cs
using BlueCardPortal.Core.Contracts;
using BlueCardPortal.Core.Extensions;
using BlueCardPortal.Extensions;
using BlueCardPortal.Infrastructure.Constants;
using BlueCardPortal.Infrastructure.Data.Models.UserContext;
using BlueCardPortal.Infrastructure.Model;
using BlueCardPortal.Infrastructure.Model.Application;
using BlueCardPortal.Infrastructure.Model.ApplicationList;
using BlueCardPortal.Infrastructure.Model.Complaint;
using BlueCardPortal.Infrastructure.Model.SelfDenial;
using BlueCardPortal.Models;
using BlueCardPortal.Resources;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Security.AccessControl;
using System.Web;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace BlueCardPortal.Controllers
{
    public class ApplicationController : BaseController
    {
        private readonly INomenclatureService nomenclatureService;
        private readonly IApplicationService applicationService;
        private readonly IStringLocalizer localizer;
        public ApplicationController(
            INomenclatureService _nomenclatureService,
            IApplicationService _applicationService,
            IStringLocalizer _localizer)
        {
            nomenclatureService = _nomenclatureService;
            localizer = _localizer;
            applicationService = _applicationService;
        }

        public async Task<IActionResult> ListApplication([FromBody] GridRequestModel request)
        {
            var data = await applicationService.GetApplicationList();
            var model = await applicationService.FilterApplicationList(request.data, data, request.page, request.size);
           
            return new JsonResult(model);
        }
        public async Task<IActionResult> ListApplicationDraft([FromBody] GridRequestModel request)
        {
            var model = await applicationService.GetApplicationListDraft(request.page, request.size);
            return new JsonResult(model);
        }
       
        public async Task<IActionResult> Add(string? permitType)
        {
            var applicationId = Guid.NewGuid();
            if (!string.IsNullOrEmpty(permitType))
            {
                var application = await applicationService.GetApplication(applicationId);
                var appType = application.GetApplicationType()!;
                appType.PermitTypeInit = permitType;
                appType.PermitType = permitType;
                appType.ApplicationTypeCode = permitType == PERMIT_TYPE.Temporary ? APPLICATION_TYPE.Temporary : APPLICATION_TYPE.Permanent;
                await applicationService.SaveApplicationType(applicationId, appType);
            }
            return RedirectToAction(nameof(Edit), new { applicationId  });
        }
        public async Task<IActionResult> Edit(Guid applicationId)
        {
            var application = await applicationService.GetApplication(applicationId);
            await nomenclatureService.SetViewBagApplication(ViewBag, application.GetApplicationTypeCode());
            application.GetEmployer()?.SetIsCompanyAddress(true);
            application.GetApplicant()?.Person?.Employer?.SetIsCompanyAddress(true);
            return View(nameof(Edit), application);
        }
        public async Task<IActionResult> AddAddress(int index, string prefix)
        {
            var ddl = await nomenclatureService.GetNomenclatureDDL(NomenclatureTypes.ADDRESSE_TYPE, false);
            if (prefix.Contains("Employer."))
            {
                ddl = ddl.Where(x => x.Value != ADDRESSE_TYPE.Permanent && x.Value != ADDRESSE_TYPE.Current).ToList();
            }
            else
            {
                ddl = ddl.Where(x => x.Value != ADDRESSE_TYPE.Head).ToList();
            }
            var address = new AddressVM
            {
                Index = index,
                KindDDL = ddl
            };
            ViewData.TemplateInfo.HtmlFieldPrefix = $"{prefix}.Items[{index}]";
            await nomenclatureService.SetViewBagAddress(ViewBag);
            return PartialView("_Address", address);
        }
        public async Task<IActionResult> AddContact(int index, string prefix)
        {
            var contact = new ContactVM
            {
                Index = index,
            };
            ViewData.TemplateInfo.HtmlFieldPrefix = $"{prefix}.Items[{index}]";
            await nomenclatureService.SetViewBagContact(ViewBag);
            return PartialView("_Contact", contact);
        }
        public async Task<IActionResult> AddPersonIdDocument(int index, string prefix)
        {
            var personIdDocument = new PersonIdDocumentVM
            {
                Index = index,
            };
            ViewData.TemplateInfo.HtmlFieldPrefix = $"{prefix}.Items[{index}]";
            await nomenclatureService.SetViewBagPersonIdDocument(ViewBag);
            return PartialView("_PersonIdDocument", personIdDocument);
        }

        private void RemoveErrorForNotUsed(string startWith)
        {
            var errors = ModelState.Where(x => x.Value.Errors.Count > 0)
                                     .Select(x => new { x.Key, x.Value.Errors })
                                     .ToList();
            foreach (var error in errors)
            {
                if (error.Key.StartsWith(startWith))
                {
                    ModelState.Remove(error.Key);
                }
            }
        }
        private JsonResult SaveResult(string state, string message)
        {
            return Json(new { state, message });
        }

        private JsonResult SaveErrorValidation()
        {
            var message = "Невалидни данни";
            foreach (var value in ModelState.Where(x => x.Value != null && x.Value?.Errors.Count > 0))
            {
                foreach (var error in value.Value!.Errors) {
                    message += Environment.NewLine + error.ErrorMessage;
                }
            }
            return SaveResult("Error", message);
        }
        private JsonResult SaveOk(string message = "")
        {
            return SaveResult("OK", message);
        }
        [HttpPost]
        [RequestFormLimits(ValueCountLimit = 99999999)]
        public async Task<JsonResult> SaveApplicationType(Guid applicationId, [Bind(Prefix = "ApplicationType")] ApplicationTypeVM model)
        {
            if (model.ApplicationTypeCode == APPLICATION_TYPE.Temporary)
            {
                RemoveErrorForNotUsed("ApplicationType.PermitType");
                model.PermitType = PERMIT_TYPE.Temporary;

            }

            if (!ModelState.IsValid)
            {
                return SaveErrorValidation();
            }
            await applicationService.SaveApplicationType(applicationId, model);
            return SaveOk();
        }
        [HttpPost]
        [RequestFormLimits(ValueCountLimit = 99999999)]

        public async Task<JsonResult> SaveApplicant(Guid applicationId, [Bind(Prefix = "Applicant")] ApplicantVM model)
        {
            RemoveApplicantValidation(model);
            if (!ModelState.IsValid)
            {
                return SaveErrorValidation();
            }
            await applicationService.SaveApplicant(applicationId, model);
            return SaveOk();
        }
        public void RemoveDocumentValidation(DocumentsVM documents)
        {
            foreach (var document in documents.Documents)
            {
                if (!document.IsMandatory && string.IsNullOrEmpty(document.CmisId))
                {
                    RemoveErrorForNotUsed($"Documents.Documents[{document.Index}]");
                }
            }
        }

        private void RemoveApplicantValidation(ApplicantVM model)
        {
            if (model.ApplicantType == ENTITY_TYPE.Foreigner)
            {
                model.Foreigner.Identifier = model.Lnch;
                model.Foreigner.TypeIdentifier = FOREIGNER_TYPE_IDENTIFIER.InBg;
                RemoveErrorForNotUsed("Applicant.Person.Address.Kind");
                RemoveErrorForNotUsed("Applicant.Foreigner.Fid");
                RemoveErrorForNotUsed("Applicant.Egn");
                RemoveErrorForNotUsed("Applicant.Foreigner.Identifier");
                RemoveErrorForNotUsed("Applicant.Foreigner.TypeIdentifier");
                RemoveErrorForNotUsed("Applicant.Person");
            }
            if (model.ApplicantType == ENTITY_TYPE.AuthorizedPerson || model.ApplicantType == ENTITY_TYPE.Representative)
            {
                model.Person.Address.Kind = ADDRESSE_TYPE.Correspondence;
                RemoveErrorForNotUsed("Applicant.Person.Address.Kind");
                if (model.UicType == "EGN")
                {
                    RemoveErrorForNotUsed("Applicant.Lnch");
                }
                if (model.UicType == "LNCH")
                {
                    RemoveErrorForNotUsed("Applicant.Egn");
                }
                RemoveErrorForNotUsed("Applicant.Foreigner");
                if (model.Person.ApplicantRole != ApplicationRole.Representative)
                {
                    RemoveErrorForNotUsed("Applicant.Person.Employer");
                }
                if (model.Person.ApplicantRole == ApplicationRole.Representative) {
                    RemoveErrorForNotUsed("Applicant.Person.Employer.EmployeeCount");
                    RemoveErrorForNotUsed("Applicant.Person.Employer.ForeignEmployeeCount");
                    if (model.Person.Employer.ContactAddressIsSame != YESNO_TYPE.No)
                    {
                        RemoveErrorForNotUsed("Applicant.Person.Employer.ContactAddress");
                    }
                    if (model.Person.ApplicantContactAddressIsSame != YESNO_TYPE.No)
                    {

Portal/BlueCardPortal/Controllers/HomeController.cs
using BlueCardPortal.Core.Contracts;
using BlueCardPortal.Core.Services;
using BlueCardPortal.Infrastructure.Constants;
using BlueCardPortal.Infrastructure.Model.ApplicationList;
using BlueCardPortal.Infrastructure.Model.Common;
using BlueCardPortal.Infrastructure.Model.Statistics;
using BlueCardPortal.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Bcpg.Sig;
using System.Diagnostics;

namespace BlueCardPortal.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> logger;
        private readonly INomenclatureService nomenclatureService;
        private readonly IApplicationService applicationService;

        public HomeController(
            ILogger<HomeController> _logger,
            INomenclatureService _nomenclatureService,
            IApplicationService _applicationService)
        {
            nomenclatureService = _nomenclatureService;
            applicationService = _applicationService;
            logger = _logger;
        }
      
        public async Task<IActionResult> Index()
        {
            var model = new ApplicationFilterVM();
            ViewBag.PermitType_ddl = await nomenclatureService.GetNomenclatureDDL(NomenclatureTypes.PERMIT_TYPE, true);
            ViewBag.Status_ddl = await nomenclatureService.GetNomenclatureDDL(NomenclatureTypes.EXTERNAL_STATUS, true);
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }
        [AllowAnonymous]
        public IActionResult Blanks()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Dashboard()
        {
            DashboardFilter model = new();
            await DashboardViewBag();
            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Dashboard(DashboardFilter model)
        {
            await DashboardViewBag();
            return View(model);
        }

        private async Task DashboardViewBag()
        {
            ViewBag.PermitType_ddl = await nomenclatureService.GetNomenclatureDDL(NomenclatureTypes.PERMIT_TYPE, false);
            ViewBag.Countries_ddl = await nomenclatureService.GetNomenclatureDDL(NomenclatureTypes.COUNTRIES, false);
            ViewBag.Year_ddl = nomenclatureService.GetStatisticsYear();
        }


        [AllowAnonymous]
        public IActionResult EService()
        {
            return View();
        }
        [AllowAnonymous]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            var error = HttpContext.Features.Get<IExceptionHandlerFeature>()?.Error.Message;
            string traceId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;

            logger.LogError(error, "TraceId: {0}", traceId);

            if (error != null && error.StartsWith("ErrorAjax:"))
            {
                return PartialView("ErrorAjax", new ErrorViewModel { Message = error.Replace("ErrorAjax:", string.Empty), RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            }
            //return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            return PartialView("ErrorAjax", new ErrorViewModel { Message = "Възникна непредвидена грешка", RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task<JsonResult> PermitsSeries([FromBody] DashboardFilter model)
        {
            var result = await applicationService.GetPermitData(model);
            return Json(result);
        }

        [AllowAnonymous]
        public IActionResult AccessabilityPolicy()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult UserHelp()
        {
            return View();
        }

        public async Task<IActionResult> FeedBack()
        {
            var model = new FeedBackVM();
            ViewBag.TypeId_ddl = await nomenclatureService.GetNomenclatureCodeableDDL(NomenclatureTypesCodeable.FeedBackType);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FeedBack(FeedBackVM model)
        {
            await nomenclatureService.SaveFeedBack(model);
            TempData[MessageConstant.SuccessMessage] = "Успешен запис";
            return RedirectToAction("Index", "Home");
        }
    }
}

Portal/BlueCardPortal/Controllers/ReportController.cs
using BlueCardPortal.Core.Contracts;
using BlueCardPortal.Infrastructure.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace BlueCardPortal.Controllers
{
    public class ReportController : BaseController
    {
        private readonly INomenclatureService nomenclatureService;
        private readonly IApplicationService applicationService;
        private readonly IStringLocalizer localizer;
        public ReportController(
            INomenclatureService _nomenclatureService,
            IApplicationService _applicationService,
            IStringLocalizer _localizer)
        {
            nomenclatureService = _nomenclatureService;
            localizer = _localizer;
            applicationService = _applicationService;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult IndexComplaint()
        {
            return View();
        }
        public async Task<IActionResult> IndexOnStatus()
        {
            await nomenclatureService.SetViewBagApplicationFilter(ViewBag);
            return View();
        }

        public async Task<IActionResult> IndexOnForeigner()
        {
            await nomenclatureService.SetViewBagApplicationFilter(ViewBag);
            return View();
        }
        public async Task<IActionResult> ListComplaint([FromBody] GridRequestModel request)
        {
            var model = await applicationService.GetComplaintList(request.data, request.page, request.size);
            return new JsonResult(model);
        }

        public async Task<IActionResult> ListApplicationOnStatus([FromBody] GridRequestModel request)
        {
            var data = await applicationService.GetApplicationList();
            var model = await applicationService.FilterApplicationList(request.data, data, request.page, request.size);

            return new JsonResult(model);
        }

        public async Task<IActionResult> ListApplicationOnForeigner([FromBody] GridRequestModel request)
        {
            var data = await applicationService.GetApplicationList();
            var model = await applicationService.FilterApplicationList(request.data, data, request.page, request.size);

            return new JsonResult(model);
        }
    }
}

Portal/BlueCardPortal/Views/Home/AccessabilityPolicy.cshtml
@using Microsoft.Extensions.Localization
@inject IHtmlLocalizer<BlueCardPortal.SharedResource> Localizer
@{
    ViewData["Title"] = @Localizer["AccessabilityPolicy"];
    ViewData["MainClass"] = "page-content";
}
<h1 class="page-title">@ViewData["Title"]</h1>
<br>
<ul class="doc-template__list">
    <li>
        <a target="_blank" href="/documents/politika-za-dostapnost.pdf" data-type="pdf" class="doc-template">
            @Localizer["AccessabilityPolicy"]
        </a>
    </li>
    <li>
        <a target="_blank" href="/documents/deklaracia-za-dostypnost.pdf" data-type="pdf" class="doc-template">
            @Localizer["AccessabilityDeclaration"]
        </a>
    </li>
</ul>

Portal/BlueCardPortal/Views/Home/Blanks.cshtml
@using Microsoft.Extensions.Localization
@inject IHtmlLocalizer<BlueCardPortal.SharedResource> Localizer
@{
    ViewData["Title"] = Localizer["Blanks"];
    ViewData["GuestMenuItem"] = "Blanks";
}
<div class="page-title__header"><h1 class="page-title">@Localizer["Blanks"]</h1></div>
<ul class="doc-template__list">
    <li>
        <a target="_blank" href="/blanks/заявление-за-продължително-пребиваване-по-чл-24и-24к-33к-33л-33п-33т-зчрб.pdf" data-type="pdf" class="doc-template">
            @Localizer["BlankPdf3a"]
        </a>
    </li>
    <li>
        <a target="_blank" href="/blanks/deklaracija-za-osyshtestvjavane-na-kratkosrochna-zaetost-bez-razreshenie-za-rabota-chrez-registracija-prilojenie-5.pdf" data-type="pdf" class="doc-template">
            @Localizer["BlankPdf5"]
        </a>
    </li>
</ul>

Portal/BlueCardPortal/Views/Home/Dashboard.cshtml
@using BlueCardPortal.Infrastructure.Model.Statistics
@using Microsoft.Extensions.Localization
@inject IHtmlLocalizer<BlueCardPortal.SharedResource> Localizer
@model DashboardFilter
@{
    ViewData["Title"] = Localizer["DashboardShort"];
    ViewData["GuestMenuItem"] = "Dashboard";
}
<form id="formDashboard" name="frmDashboard" method="post" action="@Url.Action("Dashboard", "Home")">
    @Html.AntiForgeryToken()

    <div class=""><h3 class="">@Localizer["Dashboard"]</h3></div>
    <div class="statistics accordion" style="min-height: 50vh;" id="accordionStatistics">
        <div class="accordion-item">
            <h2 class="accordion-header" id="statistics-headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#statistics-collapseOne" aria-expanded="true" aria-controls="statistics-collapseOne">
                    Издадени по тип разрешения за работа в Република България
                </button>
            </h2>
            <div id="statistics-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
                <div class="accordion-body">
                    <div class="row">
                        <div class="col-6 col-lg-4">
                            @Html.EditorFor(x => x.Year, "DropDown", new { Ddl = ViewBag.Year_ddl })
                        </div>
                    </div>
                    <figure class="highcharts-figure">
                        <div id="container"></div>
                    </figure>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="statistics-headingTwo">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#statistics-collapseTwo" aria-expanded="true" aria-controls="statistics-collapseTwo">
                    Първите 10 държави извън ЕС, чиито граждани са получили разрешение
                </button>
            </h2>
            <div id="statistics-collapseTwo" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingTwo">
                <div class="accordion-body">
                    <div class="row">
                        <div class="col-6 col-lg-4">
                            @Html.EditorFor(x => x.YearCountryTop10, "DropDown", new { Ddl = ViewBag.Year_ddl })
                        </div>
                    </div>
                    <figure class="highcharts-figure highcharts-on-country-top10">
                    </figure>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="statistics-headingThree">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#statistics-collapseThree" aria-expanded="true" aria-controls="statistics-collapseThree">
                    Издадени разрешения по тип и години
                </button>
            </h2>
            <div id="statistics-collapseThree" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingThree">
                <div class="accordion-body">
                    <div class="row">
                        <div class="col-6 col-lg-4">
                            @Html.EditorFor(x => x.recapFromYear, "DropDown", new { Ddl = ViewBag.Year_ddl })
                        </div>
                        <div class="col-6 col-lg-4">
                            @Html.EditorFor(x => x.recapToYear, "DropDown", new { Ddl = ViewBag.Year_ddl })
                        </div>
                    </div>
                    <figure class="highcharts-figure highcharts-on-year">
                    </figure>
                </div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="statistics-headingFour">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#statistics-collapseFour" aria-expanded="true" aria-controls="statistics-collapseFour">
                    Издадени разрешения по тип и национална идентичност
                </button>
            </h2>
            <div id="statistics-collapseFour" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingFour">
                <div class="row">
                    <div class="col-6 col-lg-4">
                        @Html.EditorFor(x => x.YearCountry, "DropDown", new { Ddl = ViewBag.Year_ddl })
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        @Html.EditorFor(x => x.Countries, "DropDownMultiple", new { Ddl = ViewBag.Countries_ddl })
                    </div>
                </div>
                <div class="accordion-body">
                    <figure class="highcharts-figure highcharts-on-country">
                    </figure>
                </div>
            </div>
        </div>

    </div>
</form>
<script src="~/lib/highcharts/highcharts.js"></script>
<script src="~/lib/highcharts/modules/exporting.js"></script>
<script src="~/lib/highcharts/modules/export-data.js"></script>
<script src="~/lib/highcharts/modules/accessibility.js"></script>
@section scripts
{
    <script src="~/js/dashboard.js" asp-append-version="true"></script>
}

Portal/BlueCardPortal/Views/Home/EService.cshtml
@using Microsoft.Extensions.Localization
@inject IHtmlLocalizer<BlueCardPortal.SharedResource> Localizer
@{
    ViewData["Title"] = Localizer["EService"];
    ViewData["GuestMenuItem"] = "EService";
}
<div class="page-title__header"><h1 class="page-title">@Localizer["EService"]</h1></div>
<nav class="dashboard mt-4" aria-label="dashboard navigation">
    <div class="row g-3">
        <div class="col-md-4">
            <a href="@Url.Action("Add", "Application")" class="dashboard-card">
                <div class="dashboard-card__icon dashboard-card__icon--type1">
                </div>
                <h2 class="dashboard-card__title">@Localizer["Applications"]</h2>
                <p class="dasboard-card__description">@Localizer["ApplicationsText"]</p>
            </a>
        </div>
        <div class="col-md-4">
            <a href="@Url.Action("Index", "Application")" class="dashboard-card">
                <div class="dashboard-card__icon dashboard-card__icon--type2">
                </div>
                <h2 class="dashboard-card__title">@Localizer["Complaints"]</h2>
                <p class="dasboard-card__description">@Localizer["ComplaintsText"]</p>
            </a>
        </div>
    </div>
</nav>

Portal/BlueCardPortal/Views/Home/FeedBack.cshtml
@using BlueCardPortal.Infrastructure.Model.Common
@model FeedBackVM;
@using Microsoft.Extensions.Localization
@inject IHtmlLocalizer<BlueCardPortal.SharedResource> Localizer
<form action="@Url.Action("FeedBack", "Home")" method="post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()
    <div class="row form-group  mb-2">
        <div class="col-lg-4">
            @Html.EditorFor(x => x.TypeId, "DropDownLong")
        </div>
        <div class="col-lg-4">
            @Html.EditorFor(x => x.Name, "StringNullable")
        </div>
        <div class="col-lg-4">
            @Html.EditorFor(x => x.Email, "StringNullable")
        </div>
    </div>
    <div class="row form-group mb-2">
        <div class="col-12">
            @Html.EditorFor(x => x.Message, "Textarea")
        </div>
    </div>
    <div class="form__footer text-right">
        <button type="button" class="btn u-btn u-btn--close" data-toggle="tooltip" ["ButtonDeleteHint"]" aria-label="@Localizer["ButtonDeleteHint"]" onclick="GoHomeIndex()"></button>
        <button type="submit" class="btn u-btn u-btn--right">@Localizer["Save"]</button>
    </div>
</form>

Portal/BlueCardPortal/Views/Home/Index.cshtml
@using Microsoft.Extensions.Localization
@inject IHtmlLocalizer<BlueCardPortal.SharedResource> Localizer
@{
    ViewData["Title"] = Localizer["WorkPlot"];
}
<div class="page-title__header"><h1 class="page-title">@Localizer["WorkPlot"]</h1></div>
<div class="row g-3 mb-4">
    <div class="col-md-4">
        <a asp-controller="Application" asp-action="Add" class="btn u-btn u-btn--person fw-bold">@Localizer["AddApplication"]</a>
    </div>
</div>

<nav class="dashboard mt-4" aria-label="dashboard navigation">
    <div class="row g-3">
        <div class="col-md-4">
            <a href="@Url.Action("Index", "Application")" class="dashboard-card">
                <div class="dashboard-card__icon dashboard-card__icon--type1">
                </div>
                <h2 class="dashboard-card__title">@Localizer["Applications"]</h2>
                <p class="dasboard-card__description">@Localizer["ApplicationSendList"]</p>
            </a>
        </div>
        <div class="col-md-4">
            <a href="@Url.Action("IndexDraft", "Application")" class="dashboard-card">
                <div class="dashboard-card__icon dashboard-card__icon--type2">
                </div>
                <h2 class="dashboard-card__title">@Localizer["ApplicationDraftListTitle"]</h2>
                <p class="dasboard-card__description">@Localizer["ApplicationDraftList"]</p>
            </a>
        </div>
        <div class="col-md-4">
            <a href="@Url.Action("Index", "Report")" class="dashboard-card">
                <div class="dashboard-card__icon dashboard-card__icon--type3">
                </div>
                <h2 class="dashboard-card__title">@Localizer["Report"]</h2>
                <p class="dasboard-card__description">@Localizer["ReportText"]</p>
            </a>
        </div>
    </div>
</nav>
@section Styles {
    <link href="~/css/home.css" rel="stylesheet" />
}

Portal/BlueCardPortal/Views/Home/UserHelp.cshtml
@using BlueCardPortal
@using Microsoft.Extensions.Localization
@inject IHtmlLocalizer<SharedResource> Localizer
@{
    ViewData["Title"] = @Localizer["UserHelp"];
    ViewData["MainClass"] = "page-content";
}
<h1 class="page-title">@ViewData["Title"]</h1>
<br>
<ul class="doc-template__list">
    <li>
        <a target="_blank" href="/documents/rakovodstvo-na-potrebitelia.pdf" data-type="pdf" class="doc-template">
            @Localizer["UserGuide"]
        </a>
    </li>
    <li>
        <a target="_blank" href="https://youtu.be/xXbuqnvebxI" data-type="video" class="doc-template">
            @Localizer["SubmitApplication"]
        </a>
    </li>
    <li>
        <a target="_blank" href="https://youtu.be/Vv0U6sIaKnw" data-type="video" class="doc-template">
            @Localizer["SubmitApplication90days"]
        </a>
    </li>
</ul>