Portal/BlueCardPortal/Controllers/ApplicationController.cs
using BlueCardPortal.Core.Contracts;
using BlueCardPortal.Core.Extensions;
using BlueCardPortal.Extensions;
using BlueCardPortal.Infrastructure.Constants;
using BlueCardPortal.Infrastructure.Data.Models.UserContext;
using BlueCardPortal.Infrastructure.Model;
using BlueCardPortal.Infrastructure.Model.Application;
using BlueCardPortal.Infrastructure.Model.ApplicationList;
using BlueCardPortal.Infrastructure.Model.Complaint;
using BlueCardPortal.Infrastructure.Model.SelfDenial;
using BlueCardPortal.Models;
using BlueCardPortal.Resources;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Security.AccessControl;
using System.Web;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace BlueCardPortal.Controllers
{
    public class ApplicationController : BaseController
    {
        private readonly INomenclatureService nomenclatureService;
        private readonly IApplicationService applicationService;
        private readonly IStringLocalizer localizer;
        public ApplicationController(
            INomenclatureService _nomenclatureService,
            IApplicationService _applicationService,
            IStringLocalizer _localizer)
        {
            nomenclatureService = _nomenclatureService;
            localizer = _localizer;
            applicationService = _applicationService;
        }

        public async Task<IActionResult> ListApplication([FromBody] GridRequestModel request)
        {
            var data = await applicationService.GetApplicationList();
            var model = await applicationService.FilterApplicationList(request.data, data, request.page, request.size);
           
            return new JsonResult(model);
        }
        public async Task<IActionResult> ListApplicationDraft([FromBody] GridRequestModel request)
        {
            var model = await applicationService.GetApplicationListDraft(request.page, request.size);
            return new JsonResult(model);
        }
       
        public async Task<IActionResult> Add(string? permitType)
        {
            var applicationId = Guid.NewGuid();
            if (!string.IsNullOrEmpty(permitType))
            {
                var application = await applicationService.GetApplication(applicationId);
                var appType = application.GetApplicationType()!;
                appType.PermitTypeInit = permitType;
                appType.PermitType = permitType;
                appType.ApplicationTypeCode = permitType == PERMIT_TYPE.Temporary ? APPLICATION_TYPE.Temporary : APPLICATION_TYPE.Permanent;
                await applicationService.SaveApplicationType(applicationId, appType);
            }
            return RedirectToAction(nameof(Edit), new { applicationId  });
        }
        public async Task<IActionResult> Edit(Guid applicationId)
        {
            var application = await applicationService.GetApplication(applicationId);
            await nomenclatureService.SetViewBagApplication(ViewBag, application.GetApplicationTypeCode());
            application.GetEmployer()?.SetIsCompanyAddress(true);
            application.GetApplicant()?.Person?.Employer?.SetIsCompanyAddress(true);
            return View(nameof(Edit), application);
        }
        public async Task<IActionResult> AddAddress(int index, string prefix)
        {
            var ddl = await nomenclatureService.GetNomenclatureDDL(NomenclatureTypes.ADDRESSE_TYPE, false);
            if (prefix.Contains("Employer."))
            {
                ddl = ddl.Where(x => x.Value != ADDRESSE_TYPE.Permanent && x.Value != ADDRESSE_TYPE.Current).ToList();
            }
            else
            {
                ddl = ddl.Where(x => x.Value != ADDRESSE_TYPE.Head).ToList();
            }
            var address = new AddressVM
            {
                Index = index,
                KindDDL = ddl
            };
            ViewData.TemplateInfo.HtmlFieldPrefix = $"{prefix}.Items[{index}]";
            await nomenclatureService.SetViewBagAddress(ViewBag);
            return PartialView("_Address", address);
        }
        public async Task<IActionResult> AddContact(int index, string prefix)
        {
            var contact = new ContactVM
            {
                Index = index,
            };
            ViewData.TemplateInfo.HtmlFieldPrefix = $"{prefix}.Items[{index}]";
            await nomenclatureService.SetViewBagContact(ViewBag);
            return PartialView("_Contact", contact);
        }
        public async Task<IActionResult> AddPersonIdDocument(int index, string prefix)
        {
            var personIdDocument = new PersonIdDocumentVM
            {
                Index = index,
            };
            ViewData.TemplateInfo.HtmlFieldPrefix = $"{prefix}.Items[{index}]";
            await nomenclatureService.SetViewBagPersonIdDocument(ViewBag);
            return PartialView("_PersonIdDocument", personIdDocument);
        }

        private void RemoveErrorForNotUsed(string startWith)
        {
            var errors = ModelState.Where(x => x.Value.Errors.Count > 0)
                                     .Select(x => new { x.Key, x.Value.Errors })
                                     .ToList();
            foreach (var error in errors)
            {
                if (error.Key.StartsWith(startWith))
                {
                    ModelState.Remove(error.Key);
                }
            }
        }
        private JsonResult SaveResult(string state, string message)
        {
            return Json(new { state, message });
        }

        private JsonResult SaveErrorValidation()
        {
            var message = "Невалидни данни";
            foreach (var value in ModelState.Where(x => x.Value != null && x.Value?.Errors.Count > 0))
            {
                foreach (var error in value.Value!.Errors) {
                    message += Environment.NewLine + error.ErrorMessage;
                }
            }
            return SaveResult("Error", message);
        }
        private JsonResult SaveOk(string message = "")
        {
            return SaveResult("OK", message);
        }
        [HttpPost]
        [RequestFormLimits(ValueCountLimit = 99999999)]
        public async Task<JsonResult> SaveApplicationType(Guid applicationId, [Bind(Prefix = "ApplicationType")] ApplicationTypeVM model)
        {
            if (model.ApplicationTypeCode == APPLICATION_TYPE.Temporary)
            {
                RemoveErrorForNotUsed("ApplicationType.PermitType");
                model.PermitType = PERMIT_TYPE.Temporary;

            }

            if (!ModelState.IsValid)
            {
                return SaveErrorValidation();
            }
            await applicationService.SaveApplicationType(applicationId, model);
            return SaveOk();
        }
        [HttpPost]
        [RequestFormLimits(ValueCountLimit = 99999999)]

        public async Task<JsonResult> SaveApplicant(Guid applicationId, [Bind(Prefix = "Applicant")] ApplicantVM model)
        {
            RemoveApplicantValidation(model);
            if (!ModelState.IsValid)
            {
                return SaveErrorValidation();
            }
            await applicationService.SaveApplicant(applicationId, model);
            return SaveOk();
        }
        public void RemoveDocumentValidation(DocumentsVM documents)
        {
            foreach (var document in documents.Documents)
            {
                if (!document.IsMandatory && string.IsNullOrEmpty(document.CmisId))
                {
                    RemoveErrorForNotUsed($"Documents.Documents[{document.Index}]");
                }
            }
        }

        private void RemoveApplicantValidation(ApplicantVM model)
        {
            if (model.ApplicantType == ENTITY_TYPE.Foreigner)
            {
                model.Foreigner.Identifier = model.Lnch;
                model.Foreigner.TypeIdentifier = FOREIGNER_TYPE_IDENTIFIER.InBg;
                RemoveErrorForNotUsed("Applicant.Person.Address.Kind");
                RemoveErrorForNotUsed("Applicant.Foreigner.Fid");
                RemoveErrorForNotUsed("Applicant.Egn");
                RemoveErrorForNotUsed("Applicant.Foreigner.Identifier");
                RemoveErrorForNotUsed("Applicant.Foreigner.TypeIdentifier");
                RemoveErrorForNotUsed("Applicant.Person");
            }
            if (model.ApplicantType == ENTITY_TYPE.AuthorizedPerson || model.ApplicantType == ENTITY_TYPE.Representative)
            {
                model.Person.Address.Kind = ADDRESSE_TYPE.Correspondence;
                RemoveErrorForNotUsed("Applicant.Person.Address.Kind");
                if (model.UicType == "EGN")
                {
                    RemoveErrorForNotUsed("Applicant.Lnch");
                }
                if (model.UicType == "LNCH")
                {
                    RemoveErrorForNotUsed("Applicant.Egn");
                }
                RemoveErrorForNotUsed("Applicant.Foreigner");
                if (model.Person.ApplicantRole != ApplicationRole.Representative)
                {
                    RemoveErrorForNotUsed("Applicant.Person.Employer");
                }
                if (model.Person.ApplicantRole == ApplicationRole.Representative) {
                    RemoveErrorForNotUsed("Applicant.Person.Employer.EmployeeCount");
                    RemoveErrorForNotUsed("Applicant.Person.Employer.ForeignEmployeeCount");
                    if (model.Person.Employer.ContactAddressIsSame != YESNO_TYPE.No)
                    {
                        RemoveErrorForNotUsed("Applicant.Person.Employer.ContactAddress");
                    }
                    if (model.Person.ApplicantContactAddressIsSame != YESNO_TYPE.No)
                    {

Portal/BlueCardPortal/Controllers/FilesController.cs
using BlueCardPortal.Core.Contracts;
using BlueCardPortal.Core.Helper;
using BlueCardPortal.Core.Services;
using BlueCardPortal.Extensions;
using BlueCardPortal.Infrastructure.Constants;
using BlueCardPortal.Infrastructure.Model.Application;
using IO.SignTools.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Localization;
using System.ComponentModel.DataAnnotations;
using System.Security.Cryptography;

namespace BlueCardPortal.Controllers
{
    public class FilesController : BaseController
    {
        private readonly IApplicationService applicationService;
        private readonly IStringLocalizer localizer;
        private readonly IIOSignToolsService signToolsService;
        private readonly INomenclatureService nomenclatureService;
        public FilesController(
            IApplicationService _applicationService,
            IStringLocalizer _localizer,
            IIOSignToolsService _signToolsService,
            INomenclatureService _nomenclatureService)
        {
            applicationService = _applicationService;
            localizer = _localizer;
            signToolsService = _signToolsService;
            nomenclatureService = _nomenclatureService;
        }

        [HttpPost]
        public async Task<PartialViewResult> UploadFileView([FromBody] DocumentVM model)
        {
            model.MaxFileSize = await nomenclatureService.UploadFileSize();
            model.FileFormats = await nomenclatureService.UploadFileFormats();
            return PartialView("_FileUpload", model);
        }
        [HttpPost]
        [DisableRequestSizeLimit]
        public async Task<IActionResult> UploadFile(ICollection<IFormFile> files, DocumentVM model)
        {
            var result = new DocumentResultVM
            {
                Error = localizer["ErrorNoFIle"]
            };
            if (files != null && files.Count() > 0)
            {
                var file = files.FirstOrDefault();
                model.MaxFileSize = await nomenclatureService.UploadFileSize();
                if (model.MaxFileSize > 0)
                {
                    long maxSize = (long)model.MaxFileSize * 1024 * 1024;
                    if (files.Any(x => x.Length > maxSize))
                    {
                        result.Error = localizer["ErrorFileMaxSIze"];
                        return Json(result);
                    }
                }
                var fileExt = Path.GetExtension(file.FileName).Replace(".", "").ToLower();
                var fileFormats = await nomenclatureService.UploadFileFormats();
                if (!$"{fileFormats},".Contains($"{fileExt},"))
                {
                    /// message = $"Недопустим файлов формат {fileExt}, разрешено е качване на файлов във формат {fileFormats} "
                    result.Error = localizer["ErrorFileExt"];
                    return Json(result);
                }
                model.MimeType = FileHelper.GetMimeType(fileExt);
                var fileHash = string.Empty;
                using (var ms = new MemoryStream())
                {
                    file.CopyTo(ms);
                    model.FileContent = Convert.ToBase64String(ms.ToArray());
                    fileHash = signToolsService.GetHash(ms.ToArray(), HashAlgorithmName.SHA256);
                }
                model.FileName = file.FileName;
                result = await applicationService.UploadFile(model);

                if (result.IsOk)
                {
                    result.FileHash = fileHash;
                    model.CmisId = result.CmisId!;
                    model.FileHash = fileHash;
                    await applicationService.SaveDocument(model.ApplicationId, model);
                    ViewData.TemplateInfo.HtmlFieldPrefix = $"Documents.Documents[{model.Index}]";
                    result.View = await this.RenderViewAsync("_Document", model, true);
                    if (model.HasMultipleFile)
                    {
                        ViewData.TemplateInfo.HtmlFieldPrefix = $"Documents.Documents[{model.IndexAll}]";
                        var blank = new DocumentVM
                        {
                            Index = model.IndexAll,
                            HasMultipleFile = true,
                            ApplicationId = model.ApplicationId,
                            DocumentCategoryCode = model.DocumentCategoryCode,
                            DocumentCategory = model.DocumentCategory,
                            DocumentType = model.DocumentType,
                            DocumentTypeCode = model.DocumentTypeCode,
                            HasTitle=model.HasTitle,
                            IsMandatory=model.IsMandatory,
                            MaxFileSize=model.MaxFileSize,
                        };
                        result.View += await this.RenderViewAsync("_Document", blank, true);
                    }
                }
            }
            return Json(result);
        }

        public async Task<IActionResult> RemoveFile(Guid applicationId, Guid portalId, bool remove)
        {
            await applicationService.RemoveDocument(applicationId, portalId, remove);
            return Json(new { state = "OK" });
        }
    }
}

Portal/BlueCardPortal/Views/Shared/ErrorAjax.cshtml
@model ErrorViewModel
<p>
    @Model.Message
</p>

@if (Model.ShowRequestId)
{
    <p>
        <strong>Request ID:</strong> <code>@Model.RequestId</code>
    </p>
}

Portal/BlueCardPortal/Views/Shared/_ApplicationFilter.cshtml
@using BlueCardPortal.Infrastructure.Model.ApplicationList
@using Microsoft.Extensions.Localization
@inject IHtmlLocalizer<BlueCardPortal.SharedResource> Localizer
@model ApplicationFilterVM;
<div class="details__body offcanvas-body">
    <div class="form-container">
        <button type="button" class="btn u-btn u-btn--light u-btn--clear-search ms-auto w-100" data-bs-dismiss="offcanvas">Затвори</button>
        <h3 class="section-title">@Localizer["SearchApplicationTitle"]</h3>
        <form id="formApplicationFilter" class="search-form" action="POST">
            @Html.AntiForgeryToken()
            @{
                await Html.RenderPartialAsync("_ApplicationFilterFields", Model);
            }
            <button type="button" class="btn u-btn  u-btn--light u-btn--clear-search ms-auto w-100" data-bs-dismiss="offcanvas" onclick="clearApplicationFilter()">Изчисти филтъра</button>
            <br/>
            <button type="button" class="btn u-btn  u-btn--light u-btn--search ms-auto w-100" data-bs-dismiss="offcanvas" onclick="searchApplication()">Търсене</button>
        </form>
        
    </div>
</div>

Portal/BlueCardPortal/Views/Shared/_ApplicationFilterFields.cshtml
@using BlueCardPortal.Infrastructure.Model.ApplicationList
@model ApplicationFilterVM
<div class="row">
    <div class="form-group col-md-6 mb-2">
        @Html.EditorFor(x => x.FromDate, "DateTimeNull")
    </div>
    <div class="form-group col-md-6 mb-2">
        @Html.EditorFor(x => x.ToDate, "DateTimeNull")
    </div>
</div>
<div class="row">
    <div class="form-group col-12 mb-2">
        @Html.EditorFor(x => x.ForeignerName, "StringNullable")
    </div>
</div>
<div class="row">
    <div class="form-group col-12 mb-2">
        @Html.EditorFor(x => x.ApplicationNumber, "StringNullable")
    </div>
</div>
<div class="row">
    <div class="col-12 mb-2">
        @Html.EditorFor(x => x.Status, "DropDown", new { Ddl = ViewBag.Status_ddl })
    </div>
</div>
<div class="row">
    <div class="col-12 mb-2">
        @Html.EditorFor(x => x.PermitType, "DropDown", new { Ddl = ViewBag.PermitType_ddl })
    </div>
</div>

Portal/BlueCardPortal/Views/Shared/_Document.cshtml
@using BlueCardPortal.Core.Helper
@using BlueCardPortal.Infrastructure.Model.Application
@using Microsoft.Extensions.Localization
@inject IHtmlLocalizer<BlueCardPortal.SharedResource> Localizer
@{
    var currentHtmlPrefix = ViewData.TemplateInfo.HtmlFieldPrefix;
    var indexPath = Utils.GetIndexPath(currentHtmlPrefix);
    var container_css = string.IsNullOrEmpty(Model.CmisId) ? "list-documents-body" : "list-documents-body-uploaded";
    var uploadDisplay = string.IsNullOrEmpty(Model.CmisId) ? string.Empty : "display:none";
    var previewDisplay = string.IsNullOrEmpty(Model.CmisId) ? "display:none" : string.Empty;
}
@model DocumentVM
<div class="row mb-2 document-container @container_css">
    <input type="hidden" name="@indexPath" value="@Model.Index" />
    @Html.HiddenFor(x => x.Index)
    @Html.HiddenFor(x => x.PortalId)
    @Html.HiddenFor(x => x.IsMandatory)
    @Html.HiddenFor(x => x.Id)
    @Html.HiddenFor(x => x.CmisId)
    @Html.HiddenFor(x => x.DocumentTypeCode)
    @Html.HiddenFor(x => x.DocumentType)
    @Html.HiddenFor(x => x.DocumentCategoryCode)
    @Html.HiddenFor(x => x.DocumentCategory)
    @Html.HiddenFor(x => x.FileUrl)
    @Html.HiddenFor(x => x.FileName)
    @Html.HiddenFor(x => x.HasMultipleFile)
    @Html.HiddenFor(x => x.HasTitle)
    @Html.HiddenFor(x => x.Title)
    @Html.HiddenFor(x => x.MimeType)
    @Html.HiddenFor(x => x.FileHash)
    @Html.HiddenFor(x => x.ApplicationId)
    @Html.HiddenFor(x => x.ForeignerLabel)
    @Html.HiddenFor(x => x.ForeignerSmallId)
    <div class="col-1">
        @if (Model.IsMandatory)
        {
            <img src="~/images/required-file.svg" />
        }
    </div>
    <div class="col-4">
        <div class="row">
            <div class="col-12">
                @Html.DisplayFor(x => x.DocumentTypeWithTitle, "StringNullable", new { @class = "document-title" })
            </div>
        </div>
    </div>
    <div class="col-4">
        @Html.DisplayFor(x => x.FileName, "StringNullable", new { @class = "document-file-name" })
    </div>
    <div class="col-1">
        @Html.EditorFor(x => x.IsOriginal, "BooleanTable")
    </div>
    <div class="col-2 p-2 d-flex justify-content-end">
        <div class="document-btn-container">
            <button style="@uploadDisplay" type="button"
                    class="btn u-btn u-bg--c3 u-btn--right u-btn--attach"
                    onclick="AppUploadFile(this)"
                    data-urlview="@Url.Action("UploadFileView", "Files")">
                @Localizer["Attach"]
            </button>
            <button style="@previewDisplay" type="button" class="btn u-btn u-btn--close m-2" aria-label="Изтрий" onclick="removeFile(this)"></button>
            <button style="@previewDisplay" type="button" class="btn u-btn u-btn--view m-2" aria-label="Преглед" onclick="previewFile(this)"></button>
        </div>
    </div>
</div>

Portal/BlueCardPortal/Views/Shared/_LanguagePartial.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options
@inject IOptions<RequestLocalizationOptions> LocOptions
@inject IViewLocalizer Localizer

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    Dictionary<string, string> cultureItems = new Dictionary<string, string>();

    if (LocOptions?.Value?.SupportedUICultures != null)
    {
        cultureItems = LocOptions.Value.SupportedUICultures
        .ToDictionary(k => k.Name, v => v.DisplayName);
    }

    var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}";
}

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle language-dropdown" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false" aria-label="open / close langiage toggle">
        <img src="~/images/language.svg" alt="langiage switcher image" />
    </a>
    <div class="dropdown-menu">
        @foreach (var key in cultureItems.Keys)
        {
            <a class="dropdown-item" asp-controller="Home" asp-action="SetLanguage" asp-route-culture="@key" asp-route-returnUrl="@returnUrl">@Localizer[key]</a>
        }
    </div>

</li>

Portal/BlueCardPortal/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Localization
@inject IHtmlLocalizer<BlueCardPortal.SharedResource> Localizer
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var guestMenuItem = @ViewData["GuestMenuItem"]?.ToString();
    var mainClass = @ViewData["mainClass"]?.ToString() ?? "pb-3";

    var guestMenuItemDashboard = guestMenuItem == "Dashboard" ? "active" : string.Empty;
    var guestMenuItemEService = guestMenuItem == "EService" ? "active" : string.Empty;
    var guestMenuItemBlanks = guestMenuItem == "Blanks" ? "active" : string.Empty;
}
<!DOCTYPE html>
<html lang="@requestCulture.RequestCulture.UICulture.Name">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css" />
    <link rel="stylesheet" href="~/lib/select2-bootstrap-5-theme/select2-bootstrap-5-theme.min.css" />
    <link rel="stylesheet" href="~/lib/tempus-dominus/dist/css/tempus-dominus.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/assets/css/main.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/assets/css/secondary.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/colors.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/steps.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/accessibility/accessibility.css" asp-append-version="true" />

    @await RenderSectionAsync("Styles", required: false)

</head>
<body>
    <header class="page-header">
        <div class="container-fluid">
            <a class="brand" href="/">
                <span class="small-title-text">@Localizer["SmallTitle"]</span>
                <span class="title-text">@Localizer["Title"]</span>
            </a>
            <nav class="guest-menu guest-menu--floating">
                @if (!string.IsNullOrEmpty(guestMenuItem))
                {
                    <ul class="guest-menu__list">
                        <li class="guest-menu__item"><a asp-controller="Home" asp-action="Dashboard" class="guest-menu__link @guestMenuItemDashboard">@Localizer["DashboardShort"]</a></li>
                        <li class="guest-menu__item"><a asp-controller="Home" asp-action="EService" class="guest-menu__link @guestMenuItemEService">@Localizer["EService"]</a></li>
                        <li class="guest-menu__item"><a asp-controller="Home" asp-action="Blanks" class="guest-menu__link @guestMenuItemBlanks">@Localizer["Blanks"]</a></li>
                    </ul>
                }
            </nav>
            <div class="d-flex">

                <partial name="_LoginPartial" />
                <nav aria-label="избор на език">
                    <ul class="nav justify-content-end">
                        <partial name="_LanguagePartial" />
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @{
        await Html.RenderPartialAsync("_ModalDialog");
    }
    <div class="main-container container">
        <main role="main" class="@mainClass pt-5">
            @RenderBody()
        </main>
    </div>
    @{
        await Html.RenderPartialAsync("_LayoutFooter");
    }
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery-validate/additional-methods.js"></script>
    <script src="~/lib/jquery-validate/localization/messages_bg.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/lib/select2/js/select2.full.min.js"></script>
    <script src="~/lib/select2/js/i18n/bg.js"></script>
    <script src="~/lib/tempus-dominus/dist/js/tempus-dominus.js"></script>
    <script src="~/lib/popperjs/umd/popper.js"></script>
    <script src="~/lib/tempus-dominus/dist/js/jQuery-provider.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.all.min.js"></script>
    @* <script src="~/lib/tempus-dominus/dist/plugins/customDateFormat.js"></script> *@
    <script src="~/lib/tempus-dominus/dist/plugins/fa-five.js"></script>
    <script src="~/js/tempus-dominus.bg.js"></script>
    <script src="~/lib/jquery-form/jquery.form.js"></script>
    <script src="~/lib/moment/moment-with-locales.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/common.js" asp-append-version="true"></script>
    <script src="~/js/uic-validation.js" asp-append-version="true"></script>
    <script src="~/accessibility/accessibility.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
    @{
        await Html.RenderPartialAsync("_UserMessages");
    }

</body>
</html>

Portal/BlueCardPortal/Views/Shared/_ModalDialog.cshtml
<div class="modal master-modal fade" аria-labelledby="modalDialogLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalDialogLabel">Мessage</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Затвори"></button>
            </div>
            <div class="modal-body">
                <div class="modal-form">
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

Portal/BlueCardPortal/Views/Shared/_StepData.cshtml
@using BlueCardPortal.Infrastructure.Model
@model StepItemVM
@{
    ViewData.TemplateInfo.HtmlFieldPrefix = Model.HtmlPrefix;
    var htmlFieldPrefix = ViewData.TemplateInfo.HtmlFieldPrefix;
    var show = Model.IsCurrent ? "show" : string.Empty;
    var id = $"form{Model.HtmlPrefix}";
}
<div id="@Model.CollapseName"
     class="step-data-container collapse @show"
     aria-labelledby="headingOne"
     data-bs-parent="#stepsContainer">
    <div class="row">
        <div class="col-12">
            <h2 class="form-title">@Model.Label</h2>
        </div>
    </div>
    @if (!string.IsNullOrEmpty(Model.ViewName))
    {
        <form id="@id" method="post" action="@Url.Action($"Save{Model.HtmlPrefix}", "Application")" enctype="multipart/form-data">
            @await Html.PartialAsync(Model.ViewName, Model.Data)
        </form>
    }
</div>
@{
    ViewData.TemplateInfo.HtmlFieldPrefix = htmlFieldPrefix;
}